services:

  mysql:
    image: mysql:8.0
    container_name: studyroom-mysql

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyroom
      MYSQL_USER: study
      MYSQL_PASSWORD: study1234

    ports:
      - "3307:3306"

  redis:
    image: redis:7
    container_name: studyroom-redis

    ports:
      - "6379:6379"

  app:
    # Docker Hub에서 이미 만들어진 Image를 사용
    image: taehyeong75/jpa-study-room:latest
    container_name: studyroom-app

    depends_on:
      - mysql
      - redis

    ports:
      - "8083:8083"

    environment:
      SPRING_PROFILES_ACTIVE: docker

  nginx:
    image: nginx:latest
    container_name: studyroom-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf